name: Docker CI/CD  # Name of the GitHub Actions workflow

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The workflow runs on the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out the repository code so the workflow can access it

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8  # Installs Python 3.8 for running tests and dependencies

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Installs project dependencies listed in requirements.txt

      - name: Run tests
        run: pytest tests/  # Runs tests using pytest to ensure the application is functioning correctly

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Enables Docker Buildx for better multi-platform builds

      - name: Build Docker image
        run: docker build -t inference-app .  # Builds a Docker image named "inference-app" from the current directory

      - name: Run container for testing
        run: docker run --rm inference-app  # Runs the Docker container and automatically removes it after execution
